### ISSUE TITLE
Verify if Docker is installed

### ISSUE THREAD

**Issue by robert-bor** [42BV/spring-boot-docker-postgres#5]
Run a Docker command to see if it is installed. If that fails, give proper feedback on what the dev can do to make the plugin work.

**Comment by terencewestphal** [comment]
There are a few options to choose from if you want to see if Docker is installed:

Basic check if the binary is in your `$PATH`:
```
type docker
```

Perhaps you want to know on what platform Docker is running and what version of it:
```
docker version
```
```
docker info
```

The output from both these commands can be filtered and optionally formatted as JSON:
```
docker info --format '{{.KernelVersion}}' 
```
```
docker version --format '{{json .}}
```
Ref: https://docs.docker.com/engine/reference/commandline/version/#examples

**Comment by robert-bor** [comment]
How about: 

```
docker --version
```

Results in one-liner:

```
Docker version 1.13.0, build 49bf474
```

This would be useful to log back.

**Comment by terencewestphal** [comment]
That would work just fine.
